manifest_version = 1

[package]
name = "example-c-component"
version = "1.0.0"
category = "data-collection"
subcategory = "analytics"
description = "Example C component for data collection"
documentation = "https://github.com/edgee-cloud/example-c-component"
repository = "https://github.com/edgee-cloud/example-c-component"
wit-world-version = "0.4.0"

[package.build]
command = "$(CC) dc_component.c internal/data_collection.c internal/data_collection_component_type.o -o /dev/stdout -mexec-model=reactor -Os | wasm-tools component new -o dc_component.wasm"
output_path = "./dc_component.wasm"
