manifest-version = 1

[component]
name = "example-c-component"
version = "1.0.0"
category = "data-collection"
subcategory = "analytics"
description = "Example C component for data collection"
documentation = "https://github.com/edgee-cloud/example-c-component"
repository = "https://github.com/edgee-cloud/example-c-component"
language = "C"
wit-version = "1.0.0"

[component.build]
command = "mkdir -p internal && (cd internal && wit-bindgen c ../.edgee/wit && cd ..) && $CC dc_component.c internal/data_collection.c internal/data_collection_component_type.o -mexec-model=reactor -Os && wasm-tools component new -o dc_component.wasm a.out"
output_path = "./dc_component.wasm"

[component.settings.example]
title = "Example Config Field"
type = "string"
